-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgCh60jNp2UMeieox+
Sbb0CR1QXUoUh3zGAZwkF/hIWCygCgYIKoZIzj0DAQehRANCAAQT2ENNFdlvm55R
QqF4C+tVoagBRxGlY3RcyrfuzXDNkgu2jCJTpiQvxDn46ZQNoAs7hZNPknMJqGwv
i9HU0kVD
-----END PRIVATE KEY-----