"""vendor_market update to days

Revision ID: 008d8481bee4
Revises: f7fc170fb12c
Create Date: 2024-11-13 09:13:58.240178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008d8481bee4'
down_revision = 'f7fc170fb12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_vendor_markets')
    with op.batch_alter_table('vendor_markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_day_id', sa.Integer(), nullable=True))
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('fk_vendor_markets_market_id_markets', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_vendor_markets_market_day_id_market_days'), 'market_days', ['market_day_id'], ['id'])
        batch_op.drop_column('market_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_vendor_markets_market_day_id_market_days'), type_='foreignkey')
        batch_op.create_foreign_key('fk_vendor_markets_market_id_markets', 'markets', ['market_id'], ['id'])
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('market_day_id')

    op.create_table('_alembic_tmp_vendor_markets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('market_day_id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['market_day_id'], ['market_days.id'], name='fk_vendor_markets_market_day_id_market_days'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='fk_vendor_markets_vendor_id_vendors'),
    sa.PrimaryKeyConstraint('id', name='pk_vendor_markets')
    )
    # ### end Alembic commands ###
