"""update database

Revision ID: 02a3ef6ae3ff
Revises: cd8ee7dadb56
Create Date: 2024-11-17 19:21:50.626452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02a3ef6ae3ff'
down_revision = 'cd8ee7dadb56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_vendor_notifications_vendor_user_id_vendor_users'), 'vendor_users', ['vendor_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_vendor_notifications_vendor_user_id_vendor_users'), type_='foreignkey')
        batch_op.drop_column('vendor_user_id')

    # ### end Alembic commands ###
