"""adding is_onboarded to vendors

Revision ID: 02c4b5eedcfe
Revises: e8207f6b3df8
Create Date: 2025-03-20 11:46:03.891778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c4b5eedcfe'
down_revision = 'e8207f6b3df8'
branch_labels = None
depends_on = None


def upgrade():
    # Add the new column with a default value
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_onboarded', sa.Boolean(), nullable=False, server_default=sa.text("FALSE")))

    # Update existing rows to have a default value
    op.execute("UPDATE vendors SET is_onboarded = FALSE")

    # Remove the server default (optional, keeps future inserts clean)
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('is_onboarded', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('is_onboarded')

    # ### end Alembic commands ###
