"""remove email_verified

Revision ID: 092bca2e0c22
Revises: f7b9aeaa1d38
Create Date: 2025-02-03 10:12:06.647564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092bca2e0c22'
down_revision = 'f7b9aeaa1d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
