"""new market_days

Revision ID: 0a0c8c9d4a3a
Revises: be6ec520e338
Create Date: 2024-11-11 09:43:10.517740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0c8c9d4a3a'
down_revision = 'be6ec520e338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('hour_start', sa.Time(), nullable=True),
    sa.Column('hour_end', sa.Time(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_days_market_id_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_days'))
    )
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_column('day_of_week')
        batch_op.drop_column('hour_end')
        batch_op.drop_column('hour_start')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hour_start', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('hour_end', sa.TIME(), nullable=True))
        batch_op.add_column(sa.Column('day_of_week', sa.INTEGER(), nullable=True))

    op.drop_table('market_days')
    # ### end Alembic commands ###
