"""add blog settings

Revision ID: 0a6970ddf605
Revises: a71f91f1e2e2
Create Date: 2025-02-07 15:10:33.993584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6970ddf605'
down_revision = 'a71f91f1e2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_new_blog', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_new_blog', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('text_new_blog', sa.Boolean(), nullable=False))

    with op.batch_alter_table('settings_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_new_blog', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_new_blog', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('text_new_blog', sa.Boolean(), nullable=False))

    with op.batch_alter_table('settings_vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_new_blog', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_new_blog', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('text_new_blog', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_vendors', schema=None) as batch_op:
        batch_op.drop_column('text_new_blog')
        batch_op.drop_column('email_new_blog')
        batch_op.drop_column('site_new_blog')

    with op.batch_alter_table('settings_users', schema=None) as batch_op:
        batch_op.drop_column('text_new_blog')
        batch_op.drop_column('email_new_blog')
        batch_op.drop_column('site_new_blog')

    with op.batch_alter_table('settings_admins', schema=None) as batch_op:
        batch_op.drop_column('text_new_blog')
        batch_op.drop_column('email_new_blog')
        batch_op.drop_column('site_new_blog')

    # ### end Alembic commands ###
