"""add AdminNotif market_id

Revision ID: 0c25a4f76138
Revises: 4d6ae1fbc40b
Create Date: 2025-02-14 13:41:13.559719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c25a4f76138'
down_revision = '4d6ae1fbc40b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_admin_notifications_market_id_markets'), 'markets', ['market_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_admin_notifications_market_id_markets'), type_='foreignkey')
        batch_op.drop_column('market_id')

    # ### end Alembic commands ###
