"""migration

Revision ID: 0d3fa90f5993
Revises: 550ff73434c6
Create Date: 2024-07-10 15:19:25.034904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3fa90f5993'
down_revision = '550ff73434c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendors_locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors_locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='fk_vendors_locations_vendor_id_vendors'),
    sa.PrimaryKeyConstraint('id', name='pk_vendors_locations')
    )
    # ### end Alembic commands ###
