"""add default image to market and vendor

Revision ID: 0ecf1bf4e500
Revises: c624f3b9a2a3
Create Date: 2024-12-27 13:57:52.858543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ecf1bf4e500'
down_revision = 'c624f3b9a2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_default', sa.String(), nullable=False))

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_default', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('image_default')

    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_column('image_default')

    # ### end Alembic commands ###
