"""pickup_duration is time

Revision ID: 15da9b5415d1
Revises: 7fe9f1cc3636
Create Date: 2024-11-04 09:58:20.050887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15da9b5415d1'
down_revision = '7fe9f1cc3636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.alter_column('pickup_duration',
               existing_type=sa.FLOAT(),
               type_=sa.Time(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.alter_column('pickup_duration',
               existing_type=sa.Time(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
