"""add task_id to blogs

Revision ID: 16e91e88a166
Revises: ed236b2cd275
Create Date: 2025-04-07 14:16:12.133981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e91e88a166'
down_revision = 'ed236b2cd275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
