"""Add is_admin to vendor_users

Revision ID: 173ca4c9c41d
Revises: 682210e496bc
Create Date: 2024-10-25 12:13:34.093545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173ca4c9c41d'
down_revision = '682210e496bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        # Add column with default value to prevent NULL constraint issues
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
