"""Drop username from User

Revision ID: 1bc51e6546e4
Revises: 79626b58aaae
Create Date: 2024-10-09 12:24:09.970893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc51e6546e4'
down_revision = '79626b58aaae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_vendor_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_vendor_users_vendor_id_vendors')),
    sa.ForeignKeyConstraint(['vendor_user_id'], ['vendor_users.id'], name=op.f('fk_vendor_vendor_users_vendor_user_id_vendor_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_vendor_users'))
    )
    op.drop_table('_alembic_tmp_market_favorites')
    with op.batch_alter_table('market_favorites', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('market_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_column('username')

    with op.batch_alter_table('vendor_favorites', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_favorites', schema=None) as batch_op:
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))
        batch_op.create_unique_constraint('uq_users_username', ['username'])

    with op.batch_alter_table('market_favorites', schema=None) as batch_op:
        batch_op.alter_column('market_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('_alembic_tmp_market_favorites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('market_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name='fk_market_favorites_market_id_markets'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_market_favorites_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_market_favorites')
    )
    op.drop_table('vendor_vendor_users')
    # ### end Alembic commands ###
