"""add user and vendor notify me settings

Revision ID: 1ef7d25c81e9
Revises: 05d887747607
Create Date: 2025-06-17 11:49:05.811455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef7d25c81e9'
down_revision = '05d887747607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_user_notify_me', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_user_notify_me', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('text_user_notify_me', sa.Boolean(), nullable=False))

    with op.batch_alter_table('settings_vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_vendor_notify_me', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_vendor_notify_me', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('text_vendor_notify_me', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_vendors', schema=None) as batch_op:
        batch_op.drop_column('text_vendor_notify_me')
        batch_op.drop_column('email_vendor_notify_me')
        batch_op.drop_column('site_vendor_notify_me')

    with op.batch_alter_table('settings_users', schema=None) as batch_op:
        batch_op.drop_column('text_user_notify_me')
        batch_op.drop_column('email_user_notify_me')
        batch_op.drop_column('site_user_notify_me')

    # ### end Alembic commands ###
