"""add recipe times and serve count

Revision ID: 21232fca4467
Revises: a9ab5fe30213
Create Date: 2025-04-21 13:41:38.924127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21232fca4467'
down_revision = 'a9ab5fe30213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prep_time_minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cook_time_minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_time_minutes', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('serve_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('serve_count')
        batch_op.drop_column('total_time_minutes')
        batch_op.drop_column('cook_time_minutes')
        batch_op.drop_column('prep_time_minutes')

    # ### end Alembic commands ###
