"""null to false

Revision ID: 21516c723ba2
Revises: 1ef7d25c81e9
Create Date: 2025-06-19 10:25:48.813605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21516c723ba2'
down_revision = '1ef7d25c81e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_users', schema=None) as batch_op:
        batch_op.alter_column('site_user_notify_me',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('email_user_notify_me',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('text_user_notify_me',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('settings_vendors', schema=None) as batch_op:
        batch_op.alter_column('site_vendor_notify_me',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('email_vendor_notify_me',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('text_vendor_notify_me',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_vendors', schema=None) as batch_op:
        batch_op.alter_column('text_vendor_notify_me',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('email_vendor_notify_me',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('site_vendor_notify_me',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('settings_users', schema=None) as batch_op:
        batch_op.alter_column('text_user_notify_me',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('email_user_notify_me',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('site_user_notify_me',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
