"""adding stripe_transfer_id to basket

Revision ID: 2253d3f69c86
Revises: 9e49d548ef6c
Create Date: 2025-02-26 12:23:21.358489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2253d3f69c86'
down_revision = '9e49d548ef6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transfer_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.drop_column('transfer_id')

    # ### end Alembic commands ###
