"""remove user favorites

Revision ID: 22842e1b039a
Revises: 3a4039cf550c
Create Date: 2024-08-30 14:43:20.736959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '22842e1b039a'
down_revision = '3a4039cf550c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('favorite_markets')
        batch_op.drop_column('favorite_vendors')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_vendors', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('favorite_markets', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
