"""updated VendorMarket

Revision ID: 268638668d15
Revises: 682210e496bc
Create Date: 2024-10-25 10:46:50.314184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268638668d15'
down_revision = '682210e496bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_markets', schema=None) as batch_op:
        batch_op.drop_column('day')
        batch_op.drop_column('pick_up_time')
        batch_op.drop_column('basket')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basket', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('pick_up_time', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('day', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
