"""add fee_vendor

Revision ID: 29280bb2dd96
Revises: 2b48d598fcd9
Create Date: 2025-02-12 16:06:37.518769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29280bb2dd96'
down_revision = '2b48d598fcd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fee_vendor', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.drop_column('fee_vendor')

    # ### end Alembic commands ###
