"""add market columns

Revision ID: 2b48d598fcd9
Revises: e111d3fefe48
Create Date: 2025-02-12 11:15:57.475951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b48d598fcd9'
down_revision = 'e111d3fefe48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=False))

    with op.batch_alter_table('settings_users', schema=None) as batch_op:
        batch_op.drop_column('text_vendor_review_response')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_vendor_review_response', sa.BOOLEAN(), nullable=False))

    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
