"""move market locations to settings

Revision ID: 308652bd01f7
Revises: e8b972685042
Create Date: 2025-01-21 11:23:11.489442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '308652bd01f7'
down_revision = 'e8b972685042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_locations', postgresql.JSON(astext_type=Text()), nullable=True))

    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.drop_column('market_locations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_locations', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('settings_vendors', schema=None) as batch_op:
        batch_op.drop_column('market_locations')

    # ### end Alembic commands ###
