"""yay

Revision ID: 342fe437b894
Revises: 756562af6871
Create Date: 2024-07-06 15:44:09.510824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342fe437b894'
down_revision = '756562af6871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_reviews', schema=None) as batch_op:
        batch_op.drop_column('date_time')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    with op.batch_alter_table('vendor_reviews', schema=None) as batch_op:
        batch_op.drop_column('date_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')

    with op.batch_alter_table('market_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
