"""added coordinates to market

Revision ID: 34389a570f8e
Revises: 22842e1b039a
Create Date: 2024-09-11 09:35:21.478148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34389a570f8e'
down_revision = '22842e1b039a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_column('coordinates')

    # ### end Alembic commands ###
