"""update baskets

Revision ID: 3a6d79f93793
Revises: 4ac260158054
Create Date: 2024-10-24 10:59:56.851766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6d79f93793'
down_revision = '4ac260158054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_time', sa.Time(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.drop_column('pickup_time')

    # ### end Alembic commands ###
