"""update blog table

Revision ID: 3de0dfcf69ff
Revises: ef9bc45e5744
Create Date: 2025-01-14 13:18:05.502467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de0dfcf69ff'
down_revision = 'ef9bc45e5744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('post_date')

    # ### end Alembic commands ###
