"""- to _

Revision ID: 3fd45acedaa6
Revises: 6bc6132a8039
Create Date: 2025-01-18 16:18:57.994427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fd45acedaa6'
down_revision = '6bc6132a8039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('site_report_review', sa.Boolean(), nullable=False),
    sa.Column('site_product_request', sa.Boolean(), nullable=False),
    sa.Column('email_report_review', sa.Boolean(), nullable=False),
    sa.Column('email_product_request', sa.Boolean(), nullable=False),
    sa.Column('text_report_review', sa.Boolean(), nullable=False),
    sa.Column('text_product_request', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], name=op.f('fk_settings_admins_admin_id_admin_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings_admins'))
    )
    op.create_table('settings_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('site_fav_market_new_event', sa.Boolean(), nullable=False),
    sa.Column('site_fav_market_schedule_change', sa.Boolean(), nullable=False),
    sa.Column('site_fav_market_new_vendor', sa.Boolean(), nullable=False),
    sa.Column('site_fav_market_new_basket', sa.Boolean(), nullable=False),
    sa.Column('site_fav_vendor_new_event', sa.Boolean(), nullable=False),
    sa.Column('site_fav_vendor_schedule_change', sa.Boolean(), nullable=False),
    sa.Column('site_fav_vendor_new_basket', sa.Boolean(), nullable=False),
    sa.Column('site_basket_pickup_time', sa.Boolean(), nullable=False),
    sa.Column('email_fav_market_new_event', sa.Boolean(), nullable=False),
    sa.Column('email_fav_market_schedule_change', sa.Boolean(), nullable=False),
    sa.Column('email_fav_market_new_vendor', sa.Boolean(), nullable=False),
    sa.Column('email_fav_market_new_basket', sa.Boolean(), nullable=False),
    sa.Column('email_fav_vendor_new_event', sa.Boolean(), nullable=False),
    sa.Column('email_fav_vendor_schedule_change', sa.Boolean(), nullable=False),
    sa.Column('email_fav_vendor_new_basket', sa.Boolean(), nullable=False),
    sa.Column('email_basket_pickup_time', sa.Boolean(), nullable=False),
    sa.Column('text_fav_market_schedule_change', sa.Boolean(), nullable=False),
    sa.Column('text_fav_market_new_basket', sa.Boolean(), nullable=False),
    sa.Column('text_fav_vendor_schedule_change', sa.Boolean(), nullable=False),
    sa.Column('text_basket_pickup_time', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_settings_users_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings_users'))
    )
    op.create_table('settings_vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_user_id', sa.Integer(), nullable=False),
    sa.Column('site_market_new_event', sa.Boolean(), nullable=False),
    sa.Column('site_market_schedule_change', sa.Boolean(), nullable=False),
    sa.Column('site_basket_sold', sa.Boolean(), nullable=False),
    sa.Column('email_market_new_event', sa.Boolean(), nullable=False),
    sa.Column('email_market_schedule_change', sa.Boolean(), nullable=False),
    sa.Column('email_basket_sold', sa.Boolean(), nullable=False),
    sa.Column('text_market_schedule_change', sa.Boolean(), nullable=False),
    sa.Column('text_basket_sold', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_user_id'], ['vendor_users.id'], name=op.f('fk_settings_vendors_vendor_user_id_vendor_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings_vendors'))
    )
    op.drop_table('settings-vendors')
    op.drop_table('settings-users')
    op.drop_table('settings-admins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings-admins',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('admin_id', sa.INTEGER(), nullable=False),
    sa.Column('site_report_review', sa.BOOLEAN(), nullable=False),
    sa.Column('site_product_request', sa.BOOLEAN(), nullable=False),
    sa.Column('email_report_review', sa.BOOLEAN(), nullable=False),
    sa.Column('email_product_request', sa.BOOLEAN(), nullable=False),
    sa.Column('text_report_review', sa.BOOLEAN(), nullable=False),
    sa.Column('text_product_request', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings-users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('site_fav_market_new_event', sa.BOOLEAN(), nullable=False),
    sa.Column('site_fav_market_schedule_change', sa.BOOLEAN(), nullable=False),
    sa.Column('site_fav_market_new_vendor', sa.BOOLEAN(), nullable=False),
    sa.Column('site_fav_market_new_basket', sa.BOOLEAN(), nullable=False),
    sa.Column('site_fav_vendor_new_event', sa.BOOLEAN(), nullable=False),
    sa.Column('site_fav_vendor_schedule_change', sa.BOOLEAN(), nullable=False),
    sa.Column('site_fav_vendor_new_basket', sa.BOOLEAN(), nullable=False),
    sa.Column('site_basket_pickup_time', sa.BOOLEAN(), nullable=False),
    sa.Column('email_fav_market_new_event', sa.BOOLEAN(), nullable=False),
    sa.Column('email_fav_market_schedule_change', sa.BOOLEAN(), nullable=False),
    sa.Column('email_fav_market_new_vendor', sa.BOOLEAN(), nullable=False),
    sa.Column('email_fav_market_new_basket', sa.BOOLEAN(), nullable=False),
    sa.Column('email_fav_vendor_new_event', sa.BOOLEAN(), nullable=False),
    sa.Column('email_fav_vendor_schedule_change', sa.BOOLEAN(), nullable=False),
    sa.Column('email_fav_vendor_new_basket', sa.BOOLEAN(), nullable=False),
    sa.Column('email_basket_pickup_time', sa.BOOLEAN(), nullable=False),
    sa.Column('text_fav_market_schedule_change', sa.BOOLEAN(), nullable=False),
    sa.Column('text_fav_market_new_basket', sa.BOOLEAN(), nullable=False),
    sa.Column('text_fav_vendor_schedule_change', sa.BOOLEAN(), nullable=False),
    sa.Column('text_basket_pickup_time', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings-vendors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_user_id', sa.INTEGER(), nullable=False),
    sa.Column('site_market_new_event', sa.BOOLEAN(), nullable=False),
    sa.Column('site_market_schedule_change', sa.BOOLEAN(), nullable=False),
    sa.Column('site_basket_sold', sa.BOOLEAN(), nullable=False),
    sa.Column('email_market_new_event', sa.BOOLEAN(), nullable=False),
    sa.Column('email_market_schedule_change', sa.BOOLEAN(), nullable=False),
    sa.Column('email_basket_sold', sa.BOOLEAN(), nullable=False),
    sa.Column('text_market_schedule_change', sa.BOOLEAN(), nullable=False),
    sa.Column('text_basket_sold', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_user_id'], ['vendor_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('settings_vendors')
    op.drop_table('settings_users')
    op.drop_table('settings_admins')
    # ### end Alembic commands ###
