"""add admin_id

Revision ID: 402cbb83c453
Revises: 721286b00fa5
Create Date: 2025-03-06 14:34:11.927238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402cbb83c453'
down_revision = '721286b00fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_admin_notifications_admin_id_admin_users'), 'admin_users', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_admin_notifications_admin_id_admin_users'), type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
