"""assocation tables

Revision ID: 41420b686ea2
Revises: a83e62cc9528
Create Date: 2024-07-05 13:57:43.489963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41420b686ea2'
down_revision = 'a83e62cc9528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_markets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_user_markets_market_id_markets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_markets_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'market_id', name=op.f('pk_user_markets'))
    )
    op.create_table('user_vendors',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_vendors_user_id_users')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_user_vendors_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('user_id', 'vendor_id', name=op.f('pk_user_vendors'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_vendors')
    op.drop_table('user_markets')
    # ### end Alembic commands ###
