"""add new_market_in_city setting

Revision ID: 438d907b217b
Revises: d68edf15215d
Create Date: 2025-02-17 10:56:38.786421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438d907b217b'
down_revision = 'd68edf15215d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_new_market_in_city', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_new_market_in_city', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_users', schema=None) as batch_op:
        batch_op.drop_column('email_new_market_in_city')
        batch_op.drop_column('site_new_market_in_city')

    # ### end Alembic commands ###
