"""initial migration

Revision ID: 44d27dd384fb
Revises: 
Create Date: 2024-07-05 12:45:55.480648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d27dd384fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('hours', sa.String(), nullable=True),
    sa.Column('year_round', sa.Boolean(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_markets'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('favorite_markets', sa.JSON(), nullable=True),
    sa.Column('favorite_vendors', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('based_out_of', sa.String(), nullable=True),
    sa.Column('locations', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    op.create_table('market_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_reviews_market_id_markets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_market_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_reviews'))
    )
    op.create_table('vendor_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vendor_reviews_user_id_users')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_reviews_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_reviews'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_reviews')
    op.drop_table('market_reviews')
    op.drop_table('vendors')
    op.drop_table('users')
    op.drop_table('markets')
    # ### end Alembic commands ###
