"""is_farmstand no longer nullable

Revision ID: 4755461f813a
Revises: 9deced340330
Create Date: 2025-07-02 10:43:16.325546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4755461f813a'
down_revision = '9deced340330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.alter_column('is_farmstand',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.alter_column('is_farmstand',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
