"""add products

Revision ID: 53212872e0cf
Revises: 0d1466ad1d95
Create Date: 2024-12-06 15:32:33.378630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53212872e0cf'
down_revision = '0d1466ad1d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
