"""delete text blog setting

Revision ID: 5474257c7c74
Revises: 0a6970ddf605
Create Date: 2025-02-08 14:19:40.043081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5474257c7c74'
down_revision = '0a6970ddf605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_admins', schema=None) as batch_op:
        batch_op.drop_column('text_new_blog')

    with op.batch_alter_table('settings_users', schema=None) as batch_op:
        batch_op.drop_column('text_new_blog')

    with op.batch_alter_table('settings_vendors', schema=None) as batch_op:
        batch_op.drop_column('text_new_blog')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_new_blog', sa.BOOLEAN(), nullable=False))

    with op.batch_alter_table('settings_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_new_blog', sa.BOOLEAN(), nullable=False))

    with op.batch_alter_table('settings_admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_new_blog', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
