"""add market created_at

Revision ID: 54bdbb757c4d
Revises: 4755461f813a
Create Date: 2025-07-27 11:00:48.555544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54bdbb757c4d'
down_revision = '4755461f813a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
