"""reinitialize

Revision ID: 550ff73434c6
Revises: d8ee415adc9a
Create Date: 2024-07-10 14:40:39.786860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '550ff73434c6'
down_revision = 'd8ee415adc9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors_locations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vendors_locations_locations_vendors', type_='foreignkey')
        batch_op.drop_column('locations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locations', sqlite.JSON(), nullable=False))
        batch_op.create_foreign_key('fk_vendors_locations_locations_vendors', 'vendors', ['locations'], ['locations'])

    # ### end Alembic commands ###
