"""add stripe_

Revision ID: 5636ef8350a3
Revises: 2253d3f69c86
Create Date: 2025-02-26 14:02:16.148724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5636ef8350a3'
down_revision = '2253d3f69c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_colufnpmn(sa.Column('stripe_transfer_id', sa.String(), nullable=True))
        batch_op.drop_column('transfer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transfer_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('stripe_transfer_id')

    # ### end Alembic commands ###
