"""add basket pickup times

Revision ID: 571d7c28559a
Revises: 58fd178b43b0
Create Date: 2024-12-01 11:34:37.744060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571d7c28559a'
down_revision = '58fd178b43b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_start', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('pickup_end', sa.Time(), nullable=False))
        batch_op.drop_column('pickup_time')
        batch_op.drop_column('pickup_duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_duration', sa.TIME(), nullable=False))
        batch_op.add_column(sa.Column('pickup_time', sa.TIME(), nullable=False))
        batch_op.drop_column('pickup_end')
        batch_op.drop_column('pickup_start')

    # ### end Alembic commands ###
