"""add notificaitons_sent to blogs

Revision ID: 5aceb893062f
Revises: 6ef6b48b96c6
Create Date: 2025-04-10 11:04:48.801275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aceb893062f'
down_revision = '6ef6b48b96c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('notifications_sent')

    # ### end Alembic commands ###
