"""add Ratings for markets and vendors

Revision ID: 605f0aa68512
Revises: 7663507ea327
Create Date: 2024-11-25 14:22:50.602144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605f0aa68512'
down_revision = '7663507ea327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_review_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_down', sa.Boolean(), nullable=True),
    sa.Column('vote_up', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['market_reviews.id'], name=op.f('fk_market_review_ratings_review_id_market_reviews')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_market_review_ratings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_review_ratings'))
    )
    op.create_table('vendor_review_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_down', sa.Boolean(), nullable=True),
    sa.Column('vote_up', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['vendor_reviews.id'], name=op.f('fk_vendor_review_ratings_review_id_vendor_reviews')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vendor_review_ratings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_review_ratings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_review_ratings')
    op.drop_table('market_review_ratings')
    # ### end Alembic commands ###
