"""add user coordinates

Revision ID: 60bc4d9a4ab7
Revises: 64425ba6bb94
Create Date: 2025-01-07 12:51:16.202922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60bc4d9a4ab7'
down_revision = '64425ba6bb94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinates', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('coordinates')

    # ### end Alembic commands ###
