"""add last_log_on to all user types

Revision ID: 632381ddbe80
Revises: 9280a02b3f1d
Create Date: 2025-01-12 17:09:24.623857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632381ddbe80'
down_revision = '9280a02b3f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_log_on', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_log_on', sa.DateTime(), nullable=True))

    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_log_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.drop_column('last_log_on')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_log_on')

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_column('last_log_on')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
