"""product to products list

Revision ID: 64425ba6bb94
Revises: 9ad2471c464f
Create Date: 2025-01-06 09:53:28.065826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64425ba6bb94'
down_revision = '9ad2471c464f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('products', sa.JSON(), nullable=False))
        batch_op.drop_constraint('fk_vendors_product_products', type_='foreignkey')
        batch_op.drop_column('product')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_vendors_product_products', 'products', ['product'], ['id'])
        batch_op.drop_column('products')

    # ### end Alembic commands ###
