"""notifications updates

Revision ID: 6471b1468fa6
Revises: 99c8da7f5113
Create Date: 2024-12-22 10:08:40.203688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6471b1468fa6'
down_revision = '99c8da7f5113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(), nullable=False))
        batch_op.drop_column('nav_link')

    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(), nullable=False))
        batch_op.drop_column('nav_link')

    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(), nullable=False))
        batch_op.drop_column('nav_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nav_link', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('link')

    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nav_link', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('link')

    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nav_link', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('link')

    # ### end Alembic commands ###
