"""market add hours and season dates

Revision ID: 682210e496bc
Revises: 3a6d79f93793
Create Date: 2024-10-24 11:02:27.814569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682210e496bc'
down_revision = '3a6d79f93793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
