"""add settings review response

Revision ID: 687a4899b283
Revises: 836e786347f3
Create Date: 2025-01-23 13:47:10.812404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687a4899b283'
down_revision = '836e786347f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_vendor_review_response', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_vendor_review_response', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('text_vendor_review_response', sa.Boolean(), nullable=False))

    with op.batch_alter_table('settings_vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_new_review', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_new_review', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('text_new_review', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_vendors', schema=None) as batch_op:
        batch_op.drop_column('text_new_review')
        batch_op.drop_column('email_new_review')
        batch_op.drop_column('site_new_review')

    with op.batch_alter_table('settings_users', schema=None) as batch_op:
        batch_op.drop_column('text_vendor_review_response')
        batch_op.drop_column('email_vendor_review_response')
        batch_op.drop_column('site_vendor_review_response')

    # ### end Alembic commands ###
