"""add join_date

Revision ID: 696a82a7b760
Revises: e25627b83f6d
Create Date: 2025-02-03 09:20:59.742524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696a82a7b760'
down_revision = 'e25627b83f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('join_date')

    # ### end Alembic commands ###
