"""is_admin to vendor_role

Revision ID: 6bc6132a8039
Revises: cc95e58c46b9
Create Date: 2025-01-16 14:00:25.697630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '6bc6132a8039'
down_revision = 'cc95e58c46b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_role', postgresql.JSON(astext_type=Text()), nullable=True))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sqlite.JSON(), nullable=True))
        batch_op.drop_column('vendor_role')

    # ### end Alembic commands ###
