"""add blog-favorites

Revision ID: 6bc6132a8039
Revises: cc95e58c46b9
Create Date: 2025-01-16 14:00:25.697630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '6bc6132a8039'
down_revision = 'cc95e58c46b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], name=op.f('fk_blog_favorites_blog_id_blogs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blog_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_favorites'))
    )
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=False))

    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_locations', postgresql.JSON(astext_type=Text()), nullable=True))

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('website')

    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.drop_column('market_locations')

    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('type')

    op.drop_table('blog_favorites')
    # ### end Alembic commands ###
