"""add task_id to notifs

Revision ID: 6ef6b48b96c6
Revises: 16e91e88a166
Create Date: 2025-04-07 14:35:37.178532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef6b48b96c6'
down_revision = '16e91e88a166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.String(), nullable=True))

    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.String(), nullable=True))

    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.drop_column('task_id')

    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.drop_column('task_id')

    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
