"""add new_statement setting

Revision ID: 721286b00fa5
Revises: 9172dc689dc0
Create Date: 2025-03-03 12:51:43.321376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721286b00fa5'
down_revision = '9172dc689dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_new_statement', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_new_statement', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_vendors', schema=None) as batch_op:
        batch_op.drop_column('email_new_statement')
        batch_op.drop_column('site_new_statement')

    # ### end Alembic commands ###
