"""initial migration

Revision ID: 756562af6871
Revises: 
Create Date: 2024-07-06 14:16:59.874750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756562af6871'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('hours', sa.String(), nullable=True),
    sa.Column('year_round', sa.Boolean(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_markets'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('favorite_markets', sa.String(), nullable=True),
    sa.Column('favorite_vendors', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('based_out_of', sa.String(), nullable=True),
    sa.Column('locations', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    op.create_table('market_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_reviews_market_id_markets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_market_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_reviews'))
    )
    op.create_table('user_markets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_user_markets_market_id_markets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_markets_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'market_id', name=op.f('pk_user_markets'))
    )
    op.create_table('user_vendors',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_vendors_user_id_users')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_user_vendors_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('user_id', 'vendor_id', name=op.f('pk_user_vendors'))
    )
    op.create_table('vendor_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vendor_reviews_user_id_users')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_reviews_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_reviews'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_reviews')
    op.drop_table('user_vendors')
    op.drop_table('user_markets')
    op.drop_table('market_reviews')
    op.drop_table('vendors')
    op.drop_table('users')
    op.drop_table('markets')
    # ### end Alembic commands ###
