"""add qr codes

Revision ID: 758c6764528f
Revises: 88a720e81b63
Create Date: 2024-12-12 10:26:54.155720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758c6764528f'
down_revision = '88a720e81b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_code', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], name=op.f('fk_qr_codes_basket_id_baskets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_qr_codes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qr_codes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qr_codes')
    # ### end Alembic commands ###
