"""link null true

Revision ID: 76c47418b834
Revises: c2bdd9452d5b
Create Date: 2024-12-26 11:39:33.036734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c47418b834'
down_revision = 'c2bdd9452d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
