"""Add VendorUser and VendorMarket tables

Revision ID: 79626b58aaae
Revises: d57b70489f97
Create Date: 2024-10-01 09:45:16.009154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79626b58aaae'
down_revision = 'd57b70489f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('basket', sa.Integer(), nullable=False),
    sa.Column('pick_up_time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_vendor_markets_market_id_markets')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_markets_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_markets'))
    )
    op.create_table('vendor_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_users_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_users')),
    sa.UniqueConstraint('email', name=op.f('uq_vendor_users_email'))
    )
    with op.batch_alter_table('market_favorites', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('market_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('vendor_favorites', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_favorites', schema=None) as batch_op:
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('market_favorites', schema=None) as batch_op:
        batch_op.alter_column('market_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('vendor_users')
    op.drop_table('vendor_markets')
    # ### end Alembic commands ###
