"""add schedule to markets

Revision ID: 7fe9f1cc3636
Revises: fb693dbbf775
Create Date: 2024-11-04 09:55:07.623940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe9f1cc3636'
down_revision = 'fb693dbbf775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_column('schedule')

    # ### end Alembic commands ###
