"""Add price and pick_up_duration to Basket model

Revision ID: 8204ac31902e
Revises: d3c70b8c3518
Create Date: 2024-10-29 20:00:06.873899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8204ac31902e'
down_revision = 'd3c70b8c3518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('pick_up_duration', sa.Time(), nullable=False, server_default='00:00:00'))

    # Remove server_default after adding the columns to avoid future issues
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.alter_column('price', server_default=None)
        batch_op.alter_column('pick_up_duration', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.drop_column('pick_up_duration')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
