"""add vendor response to VendorReview

Revision ID: 836e786347f3
Revises: 308652bd01f7
Create Date: 2025-01-23 13:30:34.733546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836e786347f3'
down_revision = '308652bd01f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_response', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('response_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_reviews', schema=None) as batch_op:
        batch_op.drop_column('response_date')
        batch_op.drop_column('vendor_response')

    # ### end Alembic commands ###
