"""add seasons, attribution, images, and captions

Revision ID: 842232a2c5f5
Revises: 1a42623e9045
Create Date: 2025-05-15 14:30:46.819619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '842232a2c5f5'
down_revision = '1a42623e9045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', postgresql.JSON(astext_type=Text()), nullable=True))
        batch_op.add_column(sa.Column('captions', postgresql.JSON(astext_type=Text()), nullable=True))

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attribution', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('attribution_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('seasons', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('seasons')
        batch_op.drop_column('attribution_link')
        batch_op.drop_column('attribution')

    with op.batch_alter_table('instructions', schema=None) as batch_op:
        batch_op.drop_column('captions')
        batch_op.drop_column('images')

    # ### end Alembic commands ###
