"""ingredient amount is optional

Revision ID: 84e100af4d12
Revises: 3da6259db0b2
Create Date: 2025-05-08 13:44:41.661131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e100af4d12'
down_revision = '3da6259db0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
