"""add vendor notif data

Revision ID: 85ea99a38749
Revises: 5474257c7c74
Create Date: 2025-02-09 11:07:28.869845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ea99a38749'
down_revision = '5474257c7c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
