"""added charges_enabled and payouts_enabled to Vendor table

Revision ID: 88b3da96a48d
Revises: 02c4b5eedcfe
Create Date: 2025-03-21 12:43:06.923145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b3da96a48d'
down_revision = '02c4b5eedcfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First add columns as nullable
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charges_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payouts_enabled', sa.Boolean(), nullable=True))
    
    # Update existing rows with default values
    op.execute("UPDATE vendors SET charges_enabled = 0")
    op.execute("UPDATE vendors SET payouts_enabled = 0")
    
    # Then make columns NOT NULL
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('charges_enabled', nullable=False)
        batch_op.alter_column('payouts_enabled', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('payouts_enabled')
        batch_op.drop_column('charges_enabled')

    # ### end Alembic commands ###
