"""revmove text new review setting

Revision ID: 89b9c895a384
Revises: be2fb0725546
Create Date: 2025-03-13 11:29:35.836263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b9c895a384'
down_revision = 'be2fb0725546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_vendors', schema=None) as batch_op:
        batch_op.drop_column('text_new_review')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_new_review', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
