"""address1 is optional

Revision ID: 8a3e244e1a2a
Revises: 21516c723ba2
Create Date: 2025-06-21 12:30:10.634853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3e244e1a2a'
down_revision = '21516c723ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('address_1',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('address_1',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
