"""temp null=true

Revision ID: 8a88bd07ae58
Revises: db3cd8f8498e
Create Date: 2024-10-26 10:09:37.201886

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8a88bd07ae58'
down_revision = 'db3cd8f8498e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.alter_column('sale_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('pickup_time',
               existing_type=sa.TIME(),
               nullable=True)

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('locations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locations', sqlite.JSON(), nullable=True))

    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.alter_column('pickup_time',
               existing_type=sa.TIME(),
               nullable=False)
        batch_op.alter_column('sale_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
