"""add stripe_ to columns

Revision ID: 8f0311f02273
Revises: 88b3da96a48d
Create Date: 2025-03-22 09:56:02.799568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0311f02273'
down_revision = '88b3da96a48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_is_onboarded', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('stripe_charges_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('stripe_payouts_enabled', sa.Boolean(), nullable=False))
        batch_op.drop_column('payouts_enabled')
        batch_op.drop_column('is_onboarded')
        batch_op.drop_column('charges_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charges_enabled', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('is_onboarded', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('payouts_enabled', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('stripe_payouts_enabled')
        batch_op.drop_column('stripe_charges_enabled')
        batch_op.drop_column('stripe_is_onboarded')

    # ### end Alembic commands ###
