"""add stripe_ to columns

Revision ID: 8f0311f02273
Revises: 88b3da96a48d
Create Date: 2025-03-22 09:56:02.799568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0311f02273'
down_revision = '88b3da96a48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns first
    op.add_column('vendors', sa.Column('stripe_is_onboarded', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('vendors', sa.Column('stripe_charges_enabled', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('vendors', sa.Column('stripe_payouts_enabled', sa.Boolean(), nullable=False, server_default='0'))
    
    # Then drop old columns
    op.drop_column('vendors', 'payouts_enabled')
    op.drop_column('vendors', 'is_onboarded')
    op.drop_column('vendors', 'charges_enabled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add old columns back first
    op.add_column('vendors', sa.Column('charges_enabled', sa.BOOLEAN(), nullable=False, server_default='0'))
    op.add_column('vendors', sa.Column('is_onboarded', sa.BOOLEAN(), nullable=False, server_default='0'))
    op.add_column('vendors', sa.Column('payouts_enabled', sa.BOOLEAN(), nullable=False, server_default='0'))
    
    # Then drop new columns
    op.drop_column('vendors', 'stripe_payouts_enabled')
    op.drop_column('vendors', 'stripe_charges_enabled')
    op.drop_column('vendors', 'stripe_is_onboarded')
    # ### end Alembic commands ###
