"""active_vendor can be null

Revision ID: 9280a02b3f1d
Revises: 9b06acb0578c
Create Date: 2025-01-09 11:33:54.459185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9280a02b3f1d'
down_revision = '9b06acb0578c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.alter_column('active_vendor',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.alter_column('active_vendor',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
