"""add bio to vendor

Revision ID: 9a7ea89a2f6f
Revises: adcca79f5a3a
Create Date: 2024-11-15 15:59:25.722364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7ea89a2f6f'
down_revision = 'adcca79f5a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
