"""admin_id to admin_user_id

Revision ID: 9ad2471c464f
Revises: 40a5f43c2d6c
Create Date: 2025-01-05 12:48:58.914320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad2471c464f'
down_revision = '40a5f43c2d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_blogs_admin_id_admin_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_blogs_admin_user_id_admin_users'), 'admin_users', ['admin_user_id'], ['id'])
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_blogs_admin_user_id_admin_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_blogs_admin_id_admin_users', 'admin_users', ['admin_id'], ['id'])
        batch_op.drop_column('admin_user_id')

    # ### end Alembic commands ###
