"""add active vendor vendor_id and is_admin to db JSON

Revision ID: 9b06acb0578c
Revises: 60bc4d9a4ab7
Create Date: 2025-01-08 13:51:42.482488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b06acb0578c'
down_revision = '60bc4d9a4ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_vendor_users')
    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_vendor', sa.Integer(), nullable=False))
        batch_op.alter_column('vendor_id',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               type_=sa.JSON(),
               nullable=True)
        batch_op.drop_constraint('fk_vendor_users_vendor_id_vendors', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_vendor_users_vendor_id_vendors', 'vendors', ['vendor_id'], ['id'])
        batch_op.alter_column('is_admin',
               existing_type=sa.JSON(),
               type_=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('vendor_id',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('active_vendor')

    op.create_table('vendor_vendor_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='fk_vendor_vendor_users_vendor_id_vendors'),
    sa.ForeignKeyConstraint(['vendor_user_id'], ['vendor_users.id'], name='fk_vendor_vendor_users_vendor_user_id_vendor_users'),
    sa.PrimaryKeyConstraint('id', name='pk_vendor_vendor_users')
    )
    # ### end Alembic commands ###
