"""updated basket class

Revision ID: 9b5f14fd3db7
Revises: 9c6a2aa760cb
Create Date: 2024-10-30 16:21:09.485297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5f14fd3db7'
down_revision = '9c6a2aa760cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.alter_column('pickup_duration',
               existing_type=sa.TIME(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.alter_column('pickup_duration',
               existing_type=sa.Float(),
               type_=sa.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
