"""add stripe account info to vendor table

Revision ID: 9d726f71dda5
Revises: cc5d25a1b63b
Create Date: 2025-02-13 10:39:23.534645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d726f71dda5'
down_revision = 'cc5d25a1b63b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_account_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_vendors_stripe_account_id'), ['stripe_account_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_vendors_stripe_account_id'), type_='unique')
        batch_op.drop_column('stripe_account_id')

    # ### end Alembic commands ###
