"""add is_farmstand to market

Revision ID: 9deced340330
Revises: 8a3e244e1a2a
Create Date: 2025-07-02 09:35:03.057702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9deced340330'
down_revision = '8a3e244e1a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_farmstand', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_column('is_farmstand')

    # ### end Alembic commands ###
