"""add market is_flagship

Revision ID: 9e49d548ef6c
Revises: e2c6cd88cdf7
Create Date: 2025-02-23 12:19:22.227246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e49d548ef6c'
down_revision = 'e2c6cd88cdf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_flagship', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_column('is_flagship')

    # ### end Alembic commands ###
