"""update database

Revision ID: 9eb9321d320a
Revises: 02a3ef6ae3ff
Create Date: 2024-11-17 19:29:02.582182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb9321d320a'
down_revision = '02a3ef6ae3ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.alter_column('vendor_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.alter_column('vendor_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
