"""update tables

Revision ID: a5315ad3d338
Revises: 9eb9321d320a
Create Date: 2024-11-19 10:28:05.913468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5315ad3d338'
down_revision = '9eb9321d320a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_user_notifications_market_id_markets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_notifications_user_id_users')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_user_notifications_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_notifications'))
    )
    op.create_table('admin_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('market_reviews_id', sa.Integer(), nullable=True),
    sa.Column('vendor_reviews_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['market_reviews_id'], ['market_reviews.id'], name=op.f('fk_admin_notifications_market_reviews_id_market_reviews')),
    sa.ForeignKeyConstraint(['vendor_reviews_id'], ['vendor_reviews.id'], name=op.f('fk_admin_notifications_vendor_reviews_id_vendor_reviews')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_notifications'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    op.drop_table('admin_notifications')
    op.drop_table('user_notifications')
    # ### end Alembic commands ###
