"""add market_day_id to notifs

Revision ID: a71f91f1e2e2
Revises: 1306edec316f
Create Date: 2025-02-07 14:19:18.012637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71f91f1e2e2'
down_revision = '1306edec316f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_day_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_user_notifications_market_day_id_market_days'), 'market_days', ['market_day_id'], ['id'])

    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_day_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_vendor_notifications_market_day_id_market_days'), 'market_days', ['market_day_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_vendor_notifications_market_day_id_market_days'), type_='foreignkey')
        batch_op.drop_column('market_day_id')

    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_notifications_market_day_id_market_days'), type_='foreignkey')
        batch_op.drop_column('market_day_id')

    # ### end Alembic commands ###
