"""add recipe_ingredient number

Revision ID: a7e154a1ef05
Revises: b870113d4b75
Create Date: 2025-05-06 16:11:59.869811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e154a1ef05'
down_revision = 'b870113d4b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_column('ingredient_number')

    # ### end Alembic commands ###
