"""trying

Revision ID: a83e62cc9528
Revises: 44d27dd384fb
Create Date: 2024-07-05 12:55:26.182113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a83e62cc9528'
down_revision = '44d27dd384fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('favorite_markets',
               existing_type=sqlite.JSON(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('favorite_vendors',
               existing_type=sqlite.JSON(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('favorite_vendors',
               existing_type=sa.String(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('favorite_markets',
               existing_type=sa.String(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
