"""add admin_id to admin notif

Revision ID: a9ab5fe30213
Revises: abdabf4ba7b6
Create Date: 2025-04-21 11:21:53.288178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ab5fe30213'
down_revision = 'abdabf4ba7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_admin_notifications_admin_id_admin_users'), 'admin_users', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_admin_notifications_admin_id_admin_users'), type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
