"""reinitalize database

Revision ID: b2cce7ca05b6
Revises: 
Create Date: 2024-12-22 09:59:34.918409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cce7ca05b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_users')),
    sa.UniqueConstraint('email', name=op.f('uq_admin_users_email'))
    )
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('for_user', sa.Boolean(), nullable=False),
    sa.Column('for_vendor', sa.Boolean(), nullable=False),
    sa.Column('for_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faqs'))
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('coordinates', sa.JSON(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('year_round', sa.Boolean(), nullable=True),
    sa.Column('season_start', sa.Date(), nullable=True),
    sa.Column('season_end', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_markets'))
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address_1', sa.String(), nullable=False),
    sa.Column('address_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zipcode', sa.String(length=10), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('avatar_default', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('market_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('hour_start', sa.Time(), nullable=True),
    sa.Column('hour_end', sa.Time(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_days_market_id_markets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_days'))
    )
    op.create_table('market_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_favorites_market_id_markets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_market_favorites_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_favorites'))
    )
    op.create_table('market_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_date', sa.Date(), nullable=False),
    sa.Column('is_reported', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_market_reviews_market_id_markets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_market_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_reviews'))
    )
    op.create_table('reported_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reported_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reported_reviews'))
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('product', sa.Integer(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product'], ['products.id'], name=op.f('fk_vendors_product_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    op.create_table('baskets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('market_day_id', sa.Integer(), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('pickup_start', sa.Time(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=True),
    sa.Column('is_grabbed', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('basket_value', sa.Float(), nullable=True),
    sa.Column('pickup_end', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['market_day_id'], ['market_days.id'], name=op.f('fk_baskets_market_day_id_market_days')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_baskets_user_id_users')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_baskets_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baskets'))
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=24), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_events_market_id_markets')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_events_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_table('market_review_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_down', sa.Boolean(), nullable=True),
    sa.Column('vote_up', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['market_reviews.id'], name=op.f('fk_market_review_ratings_review_id_market_reviews')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_market_review_ratings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_review_ratings'))
    )
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('nav_link', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_user_notifications_market_id_markets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_notifications_user_id_users')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_user_notifications_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_notifications'))
    )
    op.create_table('vendor_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vendor_favorites_user_id_users')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_favorites_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_favorites'))
    )
    op.create_table('vendor_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('market_day_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['market_day_id'], ['market_days.id'], name=op.f('fk_vendor_markets_market_day_id_market_days')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_markets_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_markets'))
    )
    op.create_table('vendor_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_date', sa.Date(), nullable=False),
    sa.Column('is_reported', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vendor_reviews_user_id_users')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_reviews_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_reviews'))
    )
    op.create_table('vendor_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_users_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_users')),
    sa.UniqueConstraint('email', name=op.f('uq_vendor_users_email'))
    )
    op.create_table('admin_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('nav_link', sa.String(), nullable=False),
    sa.Column('vendor_user_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_admin_notifications_vendor_id_vendors')),
    sa.ForeignKeyConstraint(['vendor_user_id'], ['vendor_users.id'], name=op.f('fk_admin_notifications_vendor_user_id_vendor_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_notifications'))
    )
    op.create_table('qr_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_code', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], name=op.f('fk_qr_codes_basket_id_baskets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_qr_codes_user_id_users')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_qr_codes_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qr_codes'))
    )
    op.create_table('vendor_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('nav_link', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_notifications_vendor_id_vendors')),
    sa.ForeignKeyConstraint(['vendor_user_id'], ['vendor_users.id'], name=op.f('fk_vendor_notifications_vendor_user_id_vendor_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_notifications'))
    )
    op.create_table('vendor_review_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_down', sa.Boolean(), nullable=True),
    sa.Column('vote_up', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['vendor_reviews.id'], name=op.f('fk_vendor_review_ratings_review_id_vendor_reviews')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vendor_review_ratings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_review_ratings'))
    )
    op.create_table('vendor_vendor_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_vendor_users_vendor_id_vendors')),
    sa.ForeignKeyConstraint(['vendor_user_id'], ['vendor_users.id'], name=op.f('fk_vendor_vendor_users_vendor_user_id_vendor_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_vendor_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_vendor_users')
    op.drop_table('vendor_review_ratings')
    op.drop_table('vendor_notifications')
    op.drop_table('qr_codes')
    op.drop_table('admin_notifications')
    op.drop_table('vendor_users')
    op.drop_table('vendor_reviews')
    op.drop_table('vendor_markets')
    op.drop_table('vendor_favorites')
    op.drop_table('user_notifications')
    op.drop_table('market_review_ratings')
    op.drop_table('events')
    op.drop_table('baskets')
    op.drop_table('vendors')
    op.drop_table('reported_reviews')
    op.drop_table('market_reviews')
    op.drop_table('market_favorites')
    op.drop_table('market_days')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('markets')
    op.drop_table('faqs')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
