"""add is_gingham_team to recipe


Revision ID: b870113d4b75
Revises: a1556cad553d
Create Date: 2025-05-06 13:35:10.492101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b870113d4b75'
down_revision = 'a1556cad553d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_gingham_team', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('is_gingham_team')

    # ### end Alembic commands ###
