"""Market day_of_week to numbers

Revision ID: bab735ebf207
Revises: c97a0ce1d175
Create Date: 2024-10-31 09:21:49.147276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab735ebf207'
down_revision = 'c97a0ce1d175'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
