"""add subcategories to vendor

Revision ID: be2fb0725546
Revises: 60ffdbf993de
Create Date: 2025-03-11 13:23:55.782023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2fb0725546'
down_revision = '60ffdbf993de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('products_subcategories', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('products_subcategories')

    # ### end Alembic commands ###
