"""Migration after reset

Revision ID: bf6f4164c403
Revises: c01d1323a599
Create Date: 2024-10-18 11:59:05.820549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6f4164c403'
down_revision = 'c01d1323a599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=True))
        batch_op.drop_column('based_out_of')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('based_out_of', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
