"""switch to time

Revision ID: c01d1323a599
Revises: 1bc51e6546e4
Create Date: 2024-10-13 10:43:45.633574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01d1323a599'
down_revision = '1bc51e6546e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_markets', schema=None) as batch_op:
        batch_op.alter_column('pick_up_time',
               existing_type=sa.VARCHAR(),
               type_=sa.Time(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_markets', schema=None) as batch_op:
        batch_op.alter_column('pick_up_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
