"""add nav-link to notifications

Revision ID: c0e6c2f3f0c2
Revises: 87f7a7f2a0f7
Create Date: 2024-12-17 10:45:55.731580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e6c2f3f0c2'
down_revision = '87f7a7f2a0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nav_link', sa.String(), nullable=False))

    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nav_link', sa.String(), nullable=False))

    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nav_link', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.drop_column('nav_link')

    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.drop_column('nav_link')

    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.drop_column('nav_link')

    # ### end Alembic commands ###
