"""add smallwares and skill_level

Revision ID: c13861b43643
Revises: a7e154a1ef05
Create Date: 2025-05-07 13:13:08.441606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13861b43643'
down_revision = 'a7e154a1ef05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smallwares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('smallware', sa.String(), nullable=False),
    sa.Column('smallware_alt', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_smallwares_recipe_id_recipes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smallwares'))
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_level', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('skill_level')

    op.drop_table('smallwares')
    # ### end Alembic commands ###
