"""add subject to notifications

Revision ID: c2bdd9452d5b
Revises: 45d7da10de4b
Create Date: 2024-12-26 11:34:57.899075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2bdd9452d5b'
down_revision = '45d7da10de4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=False))

    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=False))

    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_notifications', schema=None) as batch_op:
        batch_op.drop_column('subject')

    with op.batch_alter_table('user_notifications', schema=None) as batch_op:
        batch_op.drop_column('subject')

    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
