"""admin notificaiton null

Revision ID: c2df7345c453
Revises: 53212872e0cf
Create Date: 2024-12-08 10:45:03.848884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2df7345c453'
down_revision = '53212872e0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_admin_notifications_market_reviews_id_market_reviews', type_='foreignkey')
        batch_op.drop_constraint('fk_admin_notifications_vendor_reviews_id_vendor_reviews', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_admin_notifications_vendor_user_id_vendor_users'), 'vendor_users', ['vendor_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_admin_notifications_vendor_id_vendors'), 'vendors', ['vendor_id'], ['id'])
        batch_op.drop_column('vendor_reviews_id')
        batch_op.drop_column('market_reviews_id')

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('product',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('product',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_reviews_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('vendor_reviews_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_admin_notifications_vendor_id_vendors'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_admin_notifications_vendor_user_id_vendor_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_admin_notifications_vendor_reviews_id_vendor_reviews', 'vendor_reviews', ['vendor_reviews_id'], ['id'])
        batch_op.create_foreign_key('fk_admin_notifications_market_reviews_id_market_reviews', 'market_reviews', ['market_reviews_id'], ['id'])
        batch_op.drop_column('vendor_id')
        batch_op.drop_column('vendor_user_id')

    # ### end Alembic commands ###
