"""add is_visible

Revision ID: c624f3b9a2a3
Revises: 76c47418b834
Create Date: 2024-12-27 13:42:50.511004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c624f3b9a2a3'
down_revision = '76c47418b834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###
