"""add admin role

Revision ID: c74de946191b
Revises: 402cbb83c453
Create Date: 2025-03-06 14:40:59.503507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74de946191b'
down_revision = '402cbb83c453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_role', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_admin_notifications_admin_id_admin_users', type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_admin_notifications_admin_id_admin_users', 'admin_users', ['admin_id'], ['id'])
        batch_op.drop_column('admin_role')

    # ### end Alembic commands ###
