"""pick_up to uniform pickup, remove role

Revision ID: c97a0ce1d175
Revises: 8204ac31902e
Create Date: 2024-10-30 11:13:13.916337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c97a0ce1d175'
down_revision = '8204ac31902e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_duration', sa.Time(), nullable=False))
        batch_op.drop_column('pick_up_duration')

    with op.batch_alter_table('vendor_vendor_users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_vendor_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pick_up_duration', sa.TIME(), nullable=False))
        batch_op.drop_column('pickup_duration')

    # ### end Alembic commands ###
