"""add is_refunded

Revision ID: cc5d25a1b63b
Revises: 29280bb2dd96
Create Date: 2025-02-12 16:29:38.472667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc5d25a1b63b'
down_revision = '29280bb2dd96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_refunded', sa.Boolean(), nullable=False))
        batch_op.alter_column('is_sold',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_grabbed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.alter_column('is_grabbed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_sold',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('is_refunded')

    # ### end Alembic commands ###
