"""new vendor admin settings

Revision ID: ce7b573ec729
Revises: 8e74a268da14
Create Date: 2025-04-03 11:31:02.113224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7b573ec729'
down_revision = '8e74a268da14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_new_vendor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_new_vendor', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_admins', schema=None) as batch_op:
        batch_op.drop_column('email_new_vendor')
        batch_op.drop_column('site_new_vendor')

    # ### end Alembic commands ###
