"""update relationships

Revision ID: d3c70b8c3518
Revises: e60815018499
Create Date: 2024-10-28 12:48:42.781010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c70b8c3518'
down_revision = 'e60815018499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), nullable=False),
    sa.Column('market_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name='fk_vendor_locations_market_id_markets'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='fk_vendor_locations_vendor_id_vendors'),
    sa.PrimaryKeyConstraint('id', name='pk_vendor_locations')
    )
    # ### end Alembic commands ###
