"""add is_current to market

Revision ID: d68edf15215d
Revises: 0c25a4f76138
Create Date: 2025-02-16 11:51:24.704858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68edf15215d'
down_revision = '0c25a4f76138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_current', sa.Boolean(), nullable=False))
        batch_op.alter_column('is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.alter_column('is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('is_current')

    # ### end Alembic commands ###
