"""reinitialize

Revision ID: d8ee415adc9a
Revises: 2754617d2d17
Create Date: 2024-07-10 14:35:55.996073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ee415adc9a'
down_revision = '2754617d2d17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('locations', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['locations'], ['vendors.locations'], name=op.f('fk_vendors_locations_locations_vendors')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendors_locations_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors_locations'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendors_locations')
    # ### end Alembic commands ###
