"""added user_issues table

Revision ID: e111d3fefe48
Revises: 85ea99a38749
Create Date: 2025-02-11 14:55:46.665529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e111d3fefe48'
down_revision = '85ea99a38749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=False),
    sa.Column('issue_subtype', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], name=op.f('fk_user_issues_basket_id_baskets')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_issues_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_issues'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_issues')
    # ### end Alembic commands ###
