"""basket_value to value

Revision ID: e25627b83f6d
Revises: 687a4899b283
Create Date: 2025-02-02 13:16:39.219635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25627b83f6d'
down_revision = '687a4899b283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Float(), nullable=True))
        batch_op.drop_column('basket_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basket_value', sa.FLOAT(), nullable=True))
        batch_op.drop_column('value')

    # ### end Alembic commands ###
