"""Added payment_intent_id to receipts

Revision ID: e2c6cd88cdf7
Revises: e4214f775a23
Create Date: 2025-02-18 13:35:28.645401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c6cd88cdf7'
down_revision = 'e4214f775a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_intent_id', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('payment_intent_id')

    # ### end Alembic commands ###
