"""market add hours and season dates

Revision ID: e394a6e706cb
Revises: bf6f4164c403
Create Date: 2024-10-22 14:57:29.751846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e394a6e706cb'
down_revision = 'bf6f4164c403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hour_start', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('hour_end', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('day_of_week', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('season_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('season_end', sa.Date(), nullable=True))
        batch_op.drop_column('hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('season_end')
        batch_op.drop_column('season_start')
        batch_op.drop_column('day_of_week')
        batch_op.drop_column('hour_end')
        batch_op.drop_column('hour_start')

    # ### end Alembic commands ###
