"""revert

Revision ID: e4214f775a23
Revises: 7e5516c44df7
Create Date: 2025-02-18 12:52:58.005400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4214f775a23'
down_revision = '7e5516c44df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.drop_column('item_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_count', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
