"""reset null

Revision ID: e60815018499
Revises: 8a88bd07ae58
Create Date: 2024-10-26 10:16:33.752238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60815018499'
down_revision = '8a88bd07ae58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.alter_column('sale_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('pickup_time',
               existing_type=sa.TIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.alter_column('pickup_time',
               existing_type=sa.TIME(),
               nullable=True)
        batch_op.alter_column('sale_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
