"""basket market to market_day

Revision ID: e679f1e8e542
Revises: 008d8481bee4
Create Date: 2024-11-13 09:41:46.710922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e679f1e8e542'
down_revision = '008d8481bee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_baskets')
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_day_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_baskets_market_id_markets', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_baskets_market_day_id_market_days'), 'market_days', ['market_day_id'], ['id'])
        batch_op.drop_column('market_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_baskets_market_day_id_market_days'), type_='foreignkey')
        batch_op.create_foreign_key('fk_baskets_market_id_markets', 'markets', ['market_id'], ['id'])
        batch_op.drop_column('market_day_id')

    op.create_table('_alembic_tmp_baskets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pickup_duration', sa.TIME(), nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('sale_date', sa.DATE(), nullable=False),
    sa.Column('is_sold', sa.BOOLEAN(), nullable=True),
    sa.Column('pickup_time', sa.TIME(), nullable=False),
    sa.Column('is_grabbed', sa.BOOLEAN(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('market_day_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['market_day_id'], ['market_days.id'], name='fk_baskets_market_day_id_market_days'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_baskets_user_id_users'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='fk_baskets_vendor_id_vendors'),
    sa.PrimaryKeyConstraint('id', name='pk_baskets')
    )
    # ### end Alembic commands ###
