"""add maps and maps_organizer

Revision ID: e8207f6b3df8
Revises: 89b9c895a384
Create Date: 2025-03-20 10:34:03.225501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8207f6b3df8'
down_revision = '89b9c895a384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maps', postgresql.JSON(astext_type=Text()), nullable=True))
        batch_op.add_column(sa.Column('maps_organizer', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_column('maps_organizer')
        batch_op.drop_column('maps')

    # ### end Alembic commands ###
