"""add user vendor admin blog options

Revision ID: e8b972685042
Revises: 3fd45acedaa6
Create Date: 2025-01-20 09:55:14.458515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b972685042'
down_revision = '3fd45acedaa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('for_user', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('for_vendor', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('for_admin', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('for_admin')
        batch_op.drop_column('for_vendor')
        batch_op.drop_column('for_user')

    # ### end Alembic commands ###
