""" admin settings null False

Revision ID: ed236b2cd275
Revises: ce7b573ec729
Create Date: 2025-04-03 11:44:03.325209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed236b2cd275'
down_revision = 'ce7b573ec729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings_admins', schema=None) as batch_op:
        batch_op.alter_column('site_new_vendor',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('email_new_vendor',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=postgresql.BYTEA(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password',
               existing_type=postgresql.BYTEA(),
               nullable=True)

    with op.batch_alter_table('settings_admins', schema=None) as batch_op:
        batch_op.alter_column('email_new_vendor',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('site_new_vendor',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
