"""add notification_pending to blog

Revision ID: f20a6c20a99a
Revises: 5aceb893062f
Create Date: 2025-04-11 11:22:59.107744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20a6c20a99a'
down_revision = '5aceb893062f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_pending', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('notifications_pending')

    # ### end Alembic commands ###
