"""new address columns

Revision ID: fb2a92c2cc76
Revises: e679f1e8e542
Create Date: 2024-11-13 11:10:48.508295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2a92c2cc76'
down_revision = 'e679f1e8e542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('address_2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('zip', sa.String(length=10), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('zip')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('address_2')
        batch_op.drop_column('address_1')

    # ### end Alembic commands ###
