"""add vendor_id to QRCodes

Revision ID: f459a0b76336
Revises: 758c6764528f
Create Date: 2024-12-13 10:06:54.201199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f459a0b76336'
down_revision = '758c6764528f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_qr_codes_vendor_id_vendors'), 'vendors', ['vendor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qr_codes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_qr_codes_vendor_id_vendors'), type_='foreignkey')
        batch_op.drop_column('vendor_id')

    # ### end Alembic commands ###
