"""add last_login and login_count

Revision ID: f7b9aeaa1d38
Revises: 696a82a7b760
Create Date: 2025-02-03 09:34:41.589977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b9aeaa1d38'
down_revision = '696a82a7b760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('join_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_log_on')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_log_on')

    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('join_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_log_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_log_on', sa.DATETIME(), nullable=True))
        batch_op.drop_column('join_date')
        batch_op.drop_column('last_login')
        batch_op.drop_column('login_count')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_log_on', sa.DATETIME(), nullable=True))
        batch_op.drop_column('last_login')
        batch_op.drop_column('login_count')

    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_log_on', sa.DATETIME(), nullable=True))
        batch_op.drop_column('join_date')
        batch_op.drop_column('last_login')
        batch_op.drop_column('login_count')

    # ### end Alembic commands ###
