"""add is_reported

Revision ID: f7fc170fb12c
Revises: 0a0c8c9d4a3a
Create Date: 2024-11-12 10:33:25.450092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fc170fb12c'
down_revision = '0a0c8c9d4a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reported', sa.Boolean(), nullable=True))

    with op.batch_alter_table('vendor_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reported', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_reviews', schema=None) as batch_op:
        batch_op.drop_column('is_reported')

    with op.batch_alter_table('market_reviews', schema=None) as batch_op:
        batch_op.drop_column('is_reported')

    # ### end Alembic commands ###
